name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Baseline Scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Flask App
      run: |
        pip install flask
        nohup python ci-cd-pipeline/app.py &
        sleep 10

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://127.0.0.1:5000'
